### ISSUE TITLE
Controle text - texte par défaut (text...)

### ISSUE THREAD

**Issue by code34** [minipopov/GuiEditor#2]
Est-il possible lorsque l'on crée un contrôle de type text d'ajouter un texte par défaut comme : "text..." comme cela est fait sur les boutons.

Cela permettrait de voir directement le contrôle lorsqu'il est crée, et de pouvoir le positionner, le setter.

**Comment by akarasso** [comment]
oui

**Comment by code34** [comment]
génial 🗡

**Comment by code34** [comment]
ça marche merci :)
